FROM python:3.6

MAINTAINER Amir Raminfar <findamir@gmail.com>

# Create app directoy
WORKDIR /app

# Install dependencies
COPY ./conf/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

RUN apt-get update && apt-get install -y supervisor \
    && rm -rf /var/lib/apt/lists/*

# Copy files
COPY ./conf/supervisord-scheduler.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./app /app


CMD ["/usr/bin/supervisord"]
