FROM python:3.6

MAINTAINER Amir Raminfar <findamir@gmail.com>

# Create user
RUN useradd -ms /bin/bash clash

# Create app directoy
WORKDIR /app

# Install dependencies
COPY ./app/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY ./app /app

# Change user and chown
RUN chown -R clash:clash .
USER clash


CMD ["/usr/bin/supervisord"]
